const products = [
  {
    id: 1,
    name: "Sony WH-1000XM5",
    category: "Audio",
    price: 349.99,
    rating: 4.8,
    reviews: 2341,
    badge: "Best Seller",
    emoji: "🎧",
    desc: "Industry-leading noise cancellation with 30-hour battery life.",
  },
  {
    id: 2,
    name: 'Samsung 4K OLED 55"',
    category: "Displays",
    price: 1299.99,
    rating: 4.7,
    reviews: 987,
    badge: "Top Rated",
    emoji: "📺",
    desc: "Vivid OLED panel with AI-upscaling and 144Hz gaming mode.",
  },
  {
    id: 3,
    name: "Apple MacBook Pro M3",
    category: "Laptops",
    price: 1999.99,
    rating: 4.9,
    reviews: 3120,
    badge: "New",
    emoji: "💻",
    desc: "M3 chip with 18-hour battery, 16GB unified memory.",
  },
  {
    id: 4,
    name: "Logitech MX Master 3S",
    category: "Peripherals",
    price: 99.99,
    rating: 4.6,
    reviews: 5402,
    badge: "Popular",
    emoji: "🖱️",
    desc: "Precision 8K DPI sensor with MagSpeed scroll wheel.",
  },
  {
    id: 5,
    name: "iPad Pro 12.9\" M2",
    category: "Tablets",
    price: 1099.99,
    rating: 4.8,
    reviews: 1876,
    badge: "New",
    emoji: "📱",
    desc: "Liquid Retina XDR display with Apple Pencil support.",
  },
  {
    id: 6,
    name: "Corsair K100 RGB",
    category: "Peripherals",
    price: 229.99,
    rating: 4.5,
    reviews: 892,
    badge: null,
    emoji: "⌨️",
    desc: "Optical-mechanical switches with per-key RGB lighting.",
  },
  {
    id: 7,
    name: "GoPro HERO12 Black",
    category: "Cameras",
    price: 399.99,
    rating: 4.7,
    reviews: 1543,
    badge: "Hot",
    emoji: "📷",
    desc: "5.3K video, HyperSmooth 6.0 stabilization, waterproof to 10m.",
  },
  {
    id: 8,
    name: "NVIDIA RTX 4070 Ti",
    category: "Components",
    price: 799.99,
    rating: 4.8,
    reviews: 2209,
    badge: "Top Rated",
    emoji: "🖥️",
    desc: "Ada Lovelace architecture with DLSS 3 Frame Generation.",
  },
];

export default products;
